### ISSUE TITLE
queue->add Name vs JobId 

### ISSUE THREAD

**Issue by macedd** [HackThisSite/PHP-Bull-Scheduler#1]
There a queue I make use of custom job ids.
I can read in the code an option named `customJobId` but it is not very clear it represents the same `jobId` from **Bull**. Also I don't get what the `name` parameter in `queue->add` means.

Which field should I use in order to create the **unique jobId** into the bull queue?

**Comment by macedd** [comment]
Looking at the nodejs code I think one have to pass two options in order to make a custom job id: `jobId` and `customJobId`.

https://github.com/OptimalBits/bull/blob/4f001e0a76023594ffe9fd0336e932cbf9535bdd/lib/job.js#L67

**Comment by Kage** [comment]
Hi @thiagof thanks for the feedback.  The `$name` parameter is to define a named job (default is `__default__` if unset), this is the same behavior as in the NodeJS library.  It's been a while since I've touched this, so I'm not sure about the difference between `jobId` and `customJobId` in the NodeJS Bull library.  I would suspect they can both be set in the `$opts` parameter and work as expected but I haven't yet tested this.

Have you tried setting `jobId` in `$opts` to see if it works as expected?

**Comment by macedd** [comment]
From what I have researched the above works, but I haven't tested because I have changed this job strategy.
